---

- name: "Check for supported distribution"
  fail:
    msg: "Distribution {{ ansible_distribution + '-' + ansible_distribution_release }} is not supported yet."
  when: ansible_distribution + '-' + ansible_distribution_release not in role_supported_os
  tags:
    - install
    - configure
    - check_services

- block:
  - name: Installation
    include_tasks: "install.yml"
  tags: 
    - install

- block:
  - name: Configuration
    include_tasks: "configure.yml"
  tags: 
    - configure
    
- block:
  - name: Checking status of services
    include_tasks: "services.yml"
  tags: 
    - check_services